"""openfootball club names mapped to football-data.co.uk names (ADR 015).

The rest of the system names teams the way football-data.co.uk does, so
fixtures are renamed before they are stored. Promoted clubs need a line here
each summer; an unmapped name fails the fixtures refresh.
"""

from __future__ import annotations

from typing import Final

OPENFOOTBALL_TEAM_NAMES: Final[dict[str, dict[str, str]]] = {
    "Premier League": {
        "AFC Bournemouth": "Bournemouth",
        "Arsenal FC": "Arsenal",
        "Aston Villa FC": "Aston Villa",
        "Brentford FC": "Brentford",
        "Brighton & Hove Albion FC": "Brighton",
        "Chelsea FC": "Chelsea",
        "Coventry City FC": "Coventry",
        "Crystal Palace FC": "Crystal Palace",
        "Everton FC": "Everton",
        "Fulham FC": "Fulham",
        "Hull City AFC": "Hull",
        "Ipswich Town FC": "Ipswich",
        "Leeds United FC": "Leeds",
        "Liverpool FC": "Liverpool",
        "Manchester City FC": "Man City",
        "Manchester United FC": "Man United",
        "Newcastle United FC": "Newcastle",
        "Nottingham Forest FC": "Nott'm Forest",
        "Sunderland AFC": "Sunderland",
        "Tottenham Hotspur FC": "Tottenham",
    },
    "Bundesliga": {
        "1. FC Köln": "FC Koln",
        "1. FC Union Berlin": "Union Berlin",
        "1. FSV Mainz 05": "Mainz",
        "Bayer 04 Leverkusen": "Leverkusen",
        "Borussia Dortmund": "Dortmund",
        "Borussia Mönchengladbach": "M'gladbach",
        "Eintracht Frankfurt": "Ein Frankfurt",
        "FC Augsburg": "Augsburg",
        "FC Bayern München": "Bayern Munich",
        "FC Schalke 04": "Schalke 04",
        "Hamburger SV": "Hamburg",
        "RB Leipzig": "RB Leipzig",
        "SC Freiburg": "Freiburg",
        "SC Paderborn 07": "Paderborn",
        "SV 07 Elversberg": "Elversberg",
        "SV Werder Bremen": "Werder Bremen",
        "TSG 1899 Hoffenheim": "Hoffenheim",
        "VfB Stuttgart": "Stuttgart",
    },
    "La Liga": {
        "Athletic Club": "Ath Bilbao",
        "CA Osasuna": "Osasuna",
        "Club Atlético de Madrid": "Ath Madrid",
        "Deportivo Alavés": "Alaves",
        "Elche CF": "Elche",
        "FC Barcelona": "Barcelona",
        "Getafe CF": "Getafe",
        "Levante UD": "Levante",
        "Málaga CF": "Malaga",
        "RC Celta de Vigo": "Celta",
        "RC Deportivo La Coruña": "La Coruna",
        "RCD Espanyol de Barcelona": "Espanol",
        "Rayo Vallecano de Madrid": "Vallecano",
        "Real Betis Balompié": "Betis",
        "Real Madrid CF": "Real Madrid",
        "Real Racing Club de Santander": "Santander",
        "Real Sociedad de Fútbol": "Sociedad",
        "Sevilla FC": "Sevilla",
        "Valencia CF": "Valencia",
        "Villarreal CF": "Villarreal",
    },
    "Serie A": {
        "AC Milan": "Milan",
        "AC Monza": "Monza",
        "ACF Fiorentina": "Fiorentina",
        "AS Roma": "Roma",
        "Atalanta BC": "Atalanta",
        "Bologna FC 1909": "Bologna",
        "Cagliari Calcio": "Cagliari",
        "Como 1907": "Como",
        "FC Internazionale Milano": "Inter",
        "Frosinone Calcio": "Frosinone",
        "Genoa CFC": "Genoa",
        "Juventus FC": "Juventus",
        "Parma Calcio 1913": "Parma",
        "SS Lazio": "Lazio",
        "SSC Napoli": "Napoli",
        "Torino FC": "Torino",
        "US Lecce": "Lecce",
        "US Sassuolo Calcio": "Sassuolo",
        "Udinese Calcio": "Udinese",
        "Venezia FC": "Venezia",
    },
    "Ligue 1": {
        "AJ Auxerre": "Auxerre",
        "AS Monaco FC": "Monaco",
        "Angers SCO": "Angers",
        "ES Troyes AC": "Troyes",
        "FC Lorient": "Lorient",
        "Le Havre AC": "Le Havre",
        "Le Mans FC": "Le Mans",
        "Lille OSC": "Lille",
        "OGC Nice": "Nice",
        "Olympique Lyonnais": "Lyon",
        "Olympique de Marseille": "Marseille",
        "Paris FC": "Paris FC",
        "Paris Saint-Germain FC": "Paris SG",
        "RC Strasbourg Alsace": "Strasbourg",
        "Racing Club de Lens": "Lens",
        "Stade Brestois 29": "Brest",
        "Stade Rennais FC 1901": "Rennes",
        "Toulouse FC": "Toulouse",
    },
}
